### PR TITLE
adding demographic data to data folder

### PR DESCRIPTION
**Pull request by zoeykatzive**

### CODE REVIEW

**Comment by arielshif** [comment]
what time period is this for?

**Comment by zoeykatzive** [comment]
99% sure this is all five year data from 2022 but I'm going to do one more
commit this afternoon to just verify that

**Comment by arielshif** [comment]
perf thank you

**Comment by arielshif** [comment]
@ashlab11 feel free to approve/merge if this is fulfills the data data requirements!

**Pull request closed without merging**
